### PR TITLE
upgrade to v1.2.11

### PR DESCRIPTION
**Pull request by KrisThielemans**
Checklist
* [x] Used a [personal fork of the feedstock to propose changes](https://conda-forge.org/docs/maintainer/updating_pkgs.html#forking-and-pull-requests)
* [ ] Bumped the build number (if the version is unchanged)
* [x] Reset the build number to `0` (if the version changed)
* [x] [Re-rendered]( https://conda-forge.org/docs/maintainer/updating_pkgs.html#rerendering-feedstocks ) with the latest `conda-smithy` (Use the phrase <code>@<space/>conda-forge-admin, please rerender</code> in a comment in this PR for automated rerendering)
* [x] Ensured the license file is being packaged.

### CODE REVIEW

**Comment by KrisThielemans** [comment]
@conda-forge-admin, please rerender

**Comment by KrisThielemans** [comment]
@ghisvail would you mind merging this please? currently the conda distrib is broken, and I need it to install PETPVC on some machines...

thanks!

**Comment by ghisvail** [comment]
Hi Kris, sorry for the late reply.

I believe this issue has already been taken care of automatically by #6.

Feel free to update yours if that's not the case.

I'll ping the conda-forge admin team to add yourself as maintainer.

Best regards.

Le sam. 4 mars 2023, 09:52, Kris Thielemans ***@***.***> a
écrit :

**Comment by KrisThielemans** [comment]
indeed

**Pull request closed without merging**
